package sso.dao;

import java.util.List;
import sso.model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated
     */
    int insert(User record);

    void update(User record);

    void delete(Integer id);

    User get(Integer id);

    User getUserByName(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated
     */
    List<User> selectAll();
}
