package leader.sso.mapping;

import java.util.List;
import leader.sso.domain.User;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members
     *
     * @mbg.generated
     */
    @Insert({
        "insert into users (username, ",
        "password, enabled, authorities)",
        "values (#{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{enabled,jdbcType=BIT}, #{authorities,jdbcType=VARCHAR})"
    })
    int insert(User record);
    
    @Delete({
        "delete from users where id = #{id,jdbcType=Integer}"
    })
    void delete(Integer id);
    
    @Update({
        "update from users ",
        "set enabled=#{enabled,jdbcType=BIT} authorities = #{authorities,jdbcType=VARCHAR}",
        "where id= #{id,jdbcType=Integer}"
    })
    void update(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, username, password, enabled, authorities",
        "from users"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="enabled", property="enabled", jdbcType=JdbcType.BIT),
        @Result(column="authorities", property="authorities", jdbcType=JdbcType.VARCHAR)
    })
    List<User> selectAll();
}