package leader.sso.domain;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.enabled
     *
     * @mbg.generated
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.authorities
     *
     * @mbg.generated
     */
//    private String authorities;

    public User(){
    }
    public User(User user) {
		this.id = user.id;
		this.username = user.username;
		this.enabled = user.enabled;
//		this.authorities = user.authorities;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.id
     *
     * @return the value of members.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.id
     *
     * @param id the value for members.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.username
     *
     * @return the value of members.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.username
     *
     * @param username the value for members.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.password
     *
     * @return the value of members.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.password
     *
     * @param password the value for members.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.enabled
     *
     * @return the value of members.enabled
     *
     * @mbg.generated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.enabled
     *
     * @param enabled the value for members.enabled
     *
     * @mbg.generated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.authorities
     *
     * @return the value of members.authorities
     *
     * @mbg.generated
     */
//    public String getAuthorities() {
//        return authorities;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.authorities
     *
     * @param authorities the value for members.authorities
     *
     * @mbg.generated
     */
//    public void setAuthorities(String authorities) {
//        this.authorities = authorities;
//    }
}