package edu.ldcollege.mapping;

import edu.ldcollege.domain.LdHomeWorkFB;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface LdHomeWorkFBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LdHomeWorkFB
     *
     * @mbg.generated
     */
    @Insert({
        "insert into LdHomeWorkFB (myid, ",
        "userId, homeworkId, ",
        "LevelFlag, mark)",
        "values (#{myid,jdbcType=INTEGER}, ",
        "#{userid,jdbcType=INTEGER}, #{homeworkid,jdbcType=INTEGER}, ",
        "#{levelflag,jdbcType=CHAR}, #{mark,jdbcType=VARCHAR})"
    })
    int insert(LdHomeWorkFB record);
    
    @Update({
        "update LdHomeWorkFB set",
        "myid = #{myid,jdbcType=INTEGER},",
        "userid = #{userid,jdbcType=INTEGER},",
        "homeworkid = #{homeworkid,jdbcType=INTEGER},",
        "leverflag = #{levelflag,jdbcType=CHAR}, mark = #{mark,jdbcType=VARCHAR}",
        "and id= #{id,jdbcType=INTEGER}"
    })
    void update(LdHomeWorkFB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LdHomeWorkFB
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, myid, userId, homeworkId, LevelFlag, mark",
        "from LdHomeWorkFB where homeworkId = #{homeworkId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER),
        @Result(column="myid", property="myid", jdbcType=JdbcType.INTEGER),
        @Result(column="userId", property="userid", jdbcType=JdbcType.INTEGER),
        @Result(column="homeworkId", property="homeworkid", jdbcType=JdbcType.INTEGER),
        @Result(column="LevelFlag", property="levelflag", jdbcType=JdbcType.CHAR),
        @Result(column="mark", property="mark", jdbcType=JdbcType.VARCHAR)
    })
    List<LdHomeWorkFB> selectAll(Integer homeworkId);
}