package edu.ldcollege.domain;

public class LdHomeWorkFB {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWorkFB.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWorkFB.myid
     *
     * @mbg.generated
     */
    private Integer myid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWorkFB.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWorkFB.homeworkId
     *
     * @mbg.generated
     */
    private Integer homeworkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWorkFB.LevelFlag
     *
     * @mbg.generated
     */
    private String levelflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWorkFB.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWorkFB.id
     *
     * @return the value of LdHomeWorkFB.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWorkFB.id
     *
     * @param id the value for LdHomeWorkFB.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWorkFB.myid
     *
     * @return the value of LdHomeWorkFB.myid
     *
     * @mbg.generated
     */
    public Integer getMyid() {
        return myid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWorkFB.myid
     *
     * @param myid the value for LdHomeWorkFB.myid
     *
     * @mbg.generated
     */
    public void setMyid(Integer myid) {
        this.myid = myid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWorkFB.userId
     *
     * @return the value of LdHomeWorkFB.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWorkFB.userId
     *
     * @param userid the value for LdHomeWorkFB.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWorkFB.homeworkId
     *
     * @return the value of LdHomeWorkFB.homeworkId
     *
     * @mbg.generated
     */
    public Integer getHomeworkid() {
        return homeworkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWorkFB.homeworkId
     *
     * @param homeworkid the value for LdHomeWorkFB.homeworkId
     *
     * @mbg.generated
     */
    public void setHomeworkid(Integer homeworkid) {
        this.homeworkid = homeworkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWorkFB.LevelFlag
     *
     * @return the value of LdHomeWorkFB.LevelFlag
     *
     * @mbg.generated
     */
    public String getLevelflag() {
        return levelflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWorkFB.LevelFlag
     *
     * @param levelflag the value for LdHomeWorkFB.LevelFlag
     *
     * @mbg.generated
     */
    public void setLevelflag(String levelflag) {
        this.levelflag = levelflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWorkFB.mark
     *
     * @return the value of LdHomeWorkFB.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWorkFB.mark
     *
     * @param mark the value for LdHomeWorkFB.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}