package edu.ldcollege.domain;

import java.util.Date;

public class LdHomeWork {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWork.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWork.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWork.classId
     *
     * @mbg.generated
     */
    private Integer classid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWork.lessionId
     *
     * @mbg.generated
     */
    private Integer lessionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWork.homeworkFilePath
     *
     * @mbg.generated
     */
    private String homeworkfilepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWork.homeworkFileName
     *
     * @mbg.generated
     */
    private String homeworkfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWork.createDate
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWork.correctFlag
     *
     * @mbg.generated
     */
    private Integer correctflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWork.starCount
     *
     * @mbg.generated
     */
    private Integer starcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWork.negativeCount
     *
     * @mbg.generated
     */
    private Integer negativecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LdHomeWork.BestFlag
     *
     * @mbg.generated
     */
    private Byte bestflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWork.id
     *
     * @return the value of LdHomeWork.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWork.id
     *
     * @param id the value for LdHomeWork.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWork.userId
     *
     * @return the value of LdHomeWork.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWork.userId
     *
     * @param userid the value for LdHomeWork.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWork.classId
     *
     * @return the value of LdHomeWork.classId
     *
     * @mbg.generated
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWork.classId
     *
     * @param classid the value for LdHomeWork.classId
     *
     * @mbg.generated
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWork.lessionId
     *
     * @return the value of LdHomeWork.lessionId
     *
     * @mbg.generated
     */
    public Integer getLessionid() {
        return lessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWork.lessionId
     *
     * @param lessionid the value for LdHomeWork.lessionId
     *
     * @mbg.generated
     */
    public void setLessionid(Integer lessionid) {
        this.lessionid = lessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWork.homeworkFilePath
     *
     * @return the value of LdHomeWork.homeworkFilePath
     *
     * @mbg.generated
     */
    public String getHomeworkfilepath() {
        return homeworkfilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWork.homeworkFilePath
     *
     * @param homeworkfilepath the value for LdHomeWork.homeworkFilePath
     *
     * @mbg.generated
     */
    public void setHomeworkfilepath(String homeworkfilepath) {
        this.homeworkfilepath = homeworkfilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWork.homeworkFileName
     *
     * @return the value of LdHomeWork.homeworkFileName
     *
     * @mbg.generated
     */
    public String getHomeworkfilename() {
        return homeworkfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWork.homeworkFileName
     *
     * @param homeworkfilename the value for LdHomeWork.homeworkFileName
     *
     * @mbg.generated
     */
    public void setHomeworkfilename(String homeworkfilename) {
        this.homeworkfilename = homeworkfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWork.createDate
     *
     * @return the value of LdHomeWork.createDate
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWork.createDate
     *
     * @param createdate the value for LdHomeWork.createDate
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWork.correctFlag
     *
     * @return the value of LdHomeWork.correctFlag
     *
     * @mbg.generated
     */
    public Integer getCorrectflag() {
        return correctflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWork.correctFlag
     *
     * @param correctflag the value for LdHomeWork.correctFlag
     *
     * @mbg.generated
     */
    public void setCorrectflag(Integer correctflag) {
        this.correctflag = correctflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWork.starCount
     *
     * @return the value of LdHomeWork.starCount
     *
     * @mbg.generated
     */
    public Integer getStarcount() {
        return starcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWork.starCount
     *
     * @param starcount the value for LdHomeWork.starCount
     *
     * @mbg.generated
     */
    public void setStarcount(Integer starcount) {
        this.starcount = starcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWork.negativeCount
     *
     * @return the value of LdHomeWork.negativeCount
     *
     * @mbg.generated
     */
    public Integer getNegativecount() {
        return negativecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWork.negativeCount
     *
     * @param negativecount the value for LdHomeWork.negativeCount
     *
     * @mbg.generated
     */
    public void setNegativecount(Integer negativecount) {
        this.negativecount = negativecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LdHomeWork.BestFlag
     *
     * @return the value of LdHomeWork.BestFlag
     *
     * @mbg.generated
     */
    public Byte getBestflag() {
        return bestflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LdHomeWork.BestFlag
     *
     * @param bestflag the value for LdHomeWork.BestFlag
     *
     * @mbg.generated
     */
    public void setBestflag(Byte bestflag) {
        this.bestflag = bestflag;
    }
}